CREATE TABLE public.elko_product
(
    elpr_id serial NOT NULL,
    id integer,
    elko_code integer,
    name text,
    manufacturer_code text,
    vendor_name text,
    vendor_code text,
    catalog text,
    quantity text,
    price numeric(18, 2),
    discount_price numeric(18, 2),
    image_path text,
    thumbnail_image_path text,
    full_description text,
    currency text,
    http_description text,
    packaging_quantity smallint,
    warranty text,
    ean_code text,
    obligatory_kit smallint,
    reserved_quantity smallint,
    prom_date smallint,
    prom_quant smallint,
    quantity_for_price_2 text,
    price_2 numeric(18, 2),
    lot_number text,
    copyright_tax numeric(18, 2),
    incoming_quantity integer,
    unit_net_weight text,
    unit_net_weight_measure_unit text,
    unit_gross_weight text,
    unit_gross_weight_measure_unit text,
    shipping_box_height text,
    shipping_box_height_measure_unit text,
    shipping_box_width text,
    shipping_box_width_measure_unit text,
    shipping_box_depth text,
    shipping_box_depth_measure_unit text,
    shipping_box_weight text,
    shipping_box_weight_measure_unit text,
    version_nr integer NOT NULL,
    PRIMARY KEY (elpr_id)
);

ALTER TABLE public.elko_product
    OWNER to postgres;