CREATE TABLE elko_product (
    elpr_id bigint,
    id bigint,
    elko_code int,
    name varchar(255),
    manufacturer_code varchar(50),
	vendor_name varchar(100),
	vendor_code varchar(15),
	catalog varchar(20),
	quantity varchar(20),
	price decimal(18,2),
	discount_price decimal(18,2),
	image_path varchar(255),
	thumbnail_image_path varchar(255),
	full_description varchar(1000),
	currency varchar(10),
	http_description varchar(255),
	packaging_quantity int,
    warranty varchar(20),
	ean_code varchar(20),
    obligatory_kit int,
    reserved_quantity int,
    prom_date int,
    prom_quant int,
    quantity_for_price_2 varchar(50),
    price_2 decimal(18,2),
    lot_number varchar(50),
    copyright_tax decimal(18,2),
    incoming_quantity int,
	PRIMARY KEY (elpr_id)
);